### ISSUE TITLE
Frequent unnessary repaint

### ISSUE THREAD

**Issue by ssssssssssss** [Lapple/react-transitive-number#10]
This component may cause all the following siblings to repaint, the live demo also suffers this issue.

**Comment by 13141062188** [comment]
+1

**Comment by NeXTs** [comment]
+1
any workaround?

**Comment by NeXTs** [comment]
@Lapple could you please take a look why this might happen?

**Comment by NeXTs** [comment]
@Lapple could you please accept this PR and update npm ASAP?

I need it so much. I don't want to publish separate plugin to npm with just this fix..

**Comment by Lapple** [comment]
@NeXTs, merged and released as 3.0.1, thank you for help!

**Comment by NeXTs** [comment]
thank you for such quick response!
