### ISSUE TITLE
Support for React 0.13 was dropped on a minor release

### ISSUE THREAD

**Issue by thibaudcolas** [Lapple/react-transitive-number#4]
With React 0.14.0 as a peer dependency, the package install will fail when React 0.13.x is installed. This is all ok but since it's been pushed to npm as a minor release, it's going to break the installs of people that use npm's default version operator (`^`).

For example, if the package.json says `"react-transitive-number": "^1.1.0",` 1.2.0 is going to be fetched but will break on install because of changes in peerDependency requirements. It's a big breakage for a minor release.

Options to solve this:
- do nothing and let people upgrade to 0.14 / pin their versions
- Release a 1.3 on React 0.13, and a 2.0 with React 0.14

**Comment by Lapple** [comment]
Published both 1.3.0 and 2.0.0, deprecated 1.2.0, as per suggestion. Sorry for any inconvenience.

**Comment by thibaudcolas** [comment]
No worries I got it figured out quite quick because of the peerDependency warnings :)

Thanks for being so quick to support React 0.14 in the first place, it's going to make my life easier when it's time to upgrade.
